services:
  - type: web
    name: sesame-ai
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: API_KEY
        generateValue: true # Render will create a secure, random API key for you
